"""Glyphs for the framework figure, drawn from REAL data (moose run-to-walk clip, generated by the 303M model):
rest pose (demo frame), clean generated frames, the same frames with flow noise, the geodesic attention-bias matrix,
and per-joint description tags. Output: transparent PDFs in paper/figures/framework/glyphs/."""
import sys, json
from pathlib import Path
import numpy as np
import matplotlib; matplotlib.use("Agg")
import matplotlib.pyplot as plt
ROOT = Path(__file__).resolve().parents[3]
OUT = Path(__file__).resolve().parent / "glyphs"; OUT.mkdir(exist_ok=True)
DUMP = ROOT / "renders/clean_vis_ep289_g0/A_PZ_Alaskan_Moose_Female__d34d76e2c0a3e5b0d5e3.world.npz"
SKEL = ROOT / "dataset/ktjd17_pzh312_noik_v2/skeletons/PZ_Alaskan_Moose_Female.npz"
TEAL, CLAY, INK, GREY = "#1F6F8B", "#B5552F", "#2B2B2B", "#9A9A9A"
plt.rcParams.update({"font.family": "serif", "font.size": 6, "pdf.fonttype": 42})

z = np.load(DUMP, allow_pickle=True)
gen, rest, par = z["gen_fk"], z["demo_w"][0], z["parents"].astype(int)
names = [str(s) for s in z["joint_names"]]
sk = np.load(SKEL, allow_pickle=True); desc = [str(s) for s in sk["joint_descriptions"]]
assert [str(s) for s in sk["joint_names"]] == names, "joint order mismatch between dump and skeleton"
T, J = gen.shape[:2]
print(f"[glyphs] {z['rig']} clip {z['motion_id']} T={T} J={J} caption={z['caption']!r}")

def side(P):                       # world (+Y up): side view along the mean heading; returns x (forward), y (up)
    hips = next(i for i, s in enumerate(names) if "hips" in s.lower()); head = next(i for i, s in enumerate(names) if s.lower().endswith("head_joint"))
    hv = (gen[:, head] - gen[:, hips]).mean(0); hv[1] = 0; hv /= np.linalg.norm(hv)
    return P @ hv, P[..., 1]

def draw(ax, P, color, lw=0.9, dot=1.2, alpha=1.0, noise=0.0, seed=0):
    Q = P.copy()
    if noise > 0:
        Q = Q + np.random.default_rng(seed).normal(0, noise, Q.shape)
    x, y = side(Q)
    for j in range(J):
        p = par[j]
        if p < 0: continue
        ax.plot([x[j], x[p]], [y[j], y[p]], color=color, lw=lw, alpha=alpha, solid_capstyle="round")
    ax.scatter(x, y, s=dot, color=INK, alpha=alpha, linewidths=0, zorder=3)
    ax.set_aspect("equal"); ax.axis("off")
    return x, y

def square(fig, ax, x, y, pad=0.08):
    cx, cy = (x.max() + x.min()) / 2, (y.max() + y.min()) / 2
    r = max(np.ptp(x), np.ptp(y)) * (0.5 + pad)
    ax.set_xlim(cx - r, cx + r); ax.set_ylim(cy - r, cy + r)

bl = float(np.linalg.norm(sk["offset_parent_local"][par >= 0], axis=1).mean())
# 1. rest pose glyph (teal) -- the skeleton prompt
fig, ax = plt.subplots(figsize=(1.0, 1.0)); x, y = draw(ax, rest, TEAL, lw=1.1, dot=1.6); square(fig, ax, x, y); fig.savefig(OUT / "rest.pdf", transparent=True, bbox_inches="tight", pad_inches=0.01); plt.close(fig)
# 2. clean generated frames (grey ink) and their noisy versions (x_t at t ~ 0.5)
idx = np.linspace(0, T - 1, 4).astype(int)
for k, f in enumerate(idx):
    for tag, nz, col in (("clean", 0.0, INK), ("noisy", 0.55 * bl, GREY)):
        fig, ax = plt.subplots(figsize=(1.0, 1.0)); x, y = draw(ax, gen[f], col, lw=0.9, dot=1.0, noise=nz, seed=f)
        xc, yc = side(gen[f]); square(fig, ax, xc, yc, pad=0.25 if nz else 0.08)
        fig.savefig(OUT / f"{tag}_{k}.pdf", transparent=True, bbox_inches="tight", pad_inches=0.01); plt.close(fig)
# 3. motion strip: 5 generated poses along the path, one drawing (the model's output for THIS rig)
fig, ax = plt.subplots(figsize=(2.6, 1.0))
for f in np.linspace(0, T - 1, 5).astype(int):
    draw(ax, gen[f], CLAY, lw=0.8, dot=0.8, alpha=0.35 + 0.65 * f / (T - 1))
x, y = side(gen.reshape(-1, 3)); ax.set_xlim(x.min() - 0.3 * bl, x.max() + 0.3 * bl); ax.set_ylim(y.min() - 0.3 * bl, y.max() + 0.3 * bl)
fig.savefig(OUT / "motion_strip.pdf", transparent=True, bbox_inches="tight", pad_inches=0.01); plt.close(fig)
# 4. geodesic hop matrix -> attention bias icon (real tree of this rig)
G = np.full((J, J), np.inf); G[np.arange(J), np.arange(J)] = 0
for j in range(J):
    if par[j] >= 0: G[j, par[j]] = G[par[j], j] = 1
for k in range(J):
    G = np.minimum(G, G[:, [k]] + G[[k], :])
bias = -np.minimum(G, 8)
fig, ax = plt.subplots(figsize=(0.8, 0.8)); ax.imshow(bias, cmap="Blues_r", interpolation="nearest"); ax.axis("off")
fig.savefig(OUT / "bias.pdf", transparent=True, bbox_inches="tight", pad_inches=0.0); plt.close(fig)
# 5. rest pose with three description tags (joint semantics), tags close to their joints, short display strings
fig, ax = plt.subplots(figsize=(1.3, 1.05)); x, y = draw(ax, rest, TEAL, lw=1.2, dot=1.8)
def find(*subs):
    for s in subs:
        for i, n in enumerate(names):
            if s in n.lower(): return i
    raise KeyError(subs)
tags = [find("head_joint"), find("l_frontfoot", "frontfoot_joint.l", "frontfoot"), find("tail1", "tail01")]
short = ["“the head”", "“the left front foot”", "“the first tail vertebra”"]
offs = [(0.75, 0.55), (0.2, -0.95), (-0.85, -0.55)]
for (j, s, (dx, dy)) in zip(tags, short, offs):
    ax.annotate(s, (x[j], y[j]), (x[j] + dx * bl, y[j] + dy * bl), fontsize=4.8, color=TEAL, ha="center", va="center",
                arrowprops=dict(arrowstyle="-", color=TEAL, lw=0.45, shrinkA=0, shrinkB=1.5), bbox=dict(boxstyle="round,pad=0.22", fc="white", ec=TEAL, lw=0.4))
square(fig, ax, x, y, pad=0.32); fig.savefig(OUT / "rest_tags.pdf", transparent=True, bbox_inches="tight", pad_inches=0.01); plt.close(fig)
# 6. per-joint semantic vectors glyph: J rows x 6 cells, teal shades (illustrative pattern seeded by the description text)
rng = np.random.default_rng(3); fig, ax = plt.subplots(figsize=(0.3, 0.55)); M = rng.uniform(0.25, 1.0, (8, 6)); ax.imshow(M, cmap="Blues", vmin=0, vmax=1.3, aspect="auto"); ax.axis("off")
fig.savefig(OUT / "jointvec.pdf", transparent=True, bbox_inches="tight", pad_inches=0.0); plt.close(fig)
json.dump({"rig": str(z["rig"]), "clip": str(z["motion_id"]), "caption": str(z["caption"]), "T": int(T), "J": int(J), "frames": idx.tolist(), "tags": short,
           "ckpt": str(z["ckpt"]), "ckpt_sha256": str(z["ckpt_sha256"]), "epoch": int(z["epoch"])}, open(OUT / "glyphs_provenance.json", "w"), indent=1)
print("[glyphs] tags:", [desc[j] for j in tags]); print("[glyphs] wrote", sorted(p.name for p in OUT.glob("*.pdf")))

# 7. two more rest poses (different topologies) for the "one network, many rigs" fan: gharial and giant tortoise, side view
sys.path.insert(0, str(ROOT / "paper/figures"))
from skeleton_art import load as sk_load, project as sk_project
for rig, fname in (("PZ_Gharial_Male", "rest_gharial.pdf"), ("PZ_Red_Ruffed_Lemur_Male", "rest_lemur.pdf"), ("PZ_Alaskan_Moose_Female", "rest_moose_plain.pdf")):
    P, par_, names_ = sk_load(ROOT / f"dataset/ktjd17_pzh312_noik_v2/skeletons/{rig}.npz")
    x, y, dpt = sk_project(P, "side")
    fig, ax = plt.subplots(figsize=(1.0, 0.7))
    for j in np.argsort(dpt):
        p_ = par_[j]
        if p_ < 0: continue
        ax.plot([x[j], x[p_]], [y[j], y[p_]], color=TEAL, lw=0.9, solid_capstyle="round")
    ax.scatter(x, y, s=1.0, color=INK, linewidths=0, zorder=3); ax.set_aspect("equal"); ax.axis("off")
    cx, cy = (x.max() + x.min()) / 2, (y.max() + y.min()) / 2; r = max(np.ptp(x), np.ptp(y)) * 0.56
    ax.set_xlim(cx - r, cx + r); ax.set_ylim(cy - r * 0.7, cy + r * 0.7)
    fig.savefig(OUT / fname, transparent=True, bbox_inches="tight", pad_inches=0.01); plt.close(fig)
print("[glyphs] fan glyphs written")
